steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/omega-portal-415507/softbank-hackathon4', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'softbank-hackathon4', '--image', 'gcr.io/omega-portal-415507/softbank-hackathon4:latest', '--region', 'us-central1']
logsBucket: 'gs://abllu-softbank-hackathon'
images:
- 'gcr.io/omega-portal-415507/softbank-hackathon4'
